import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/shared/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      xs: "321px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1080px",
      "2xl": "1281px",
      "3xl": "1536px",
      "4xl": "1649px",
      "4_2xl": "1880px",
      "5xl": "2048px",
    },
    extend: {
      lineHeight: {
        64: "4rem",
        52: "3.25rem",
        44: "2.75rem",
        40: "2.5rem",
        36: "2.25rem",
        32: "2rem",
        28: "1.75rem",
        24: "1.5rem",
        20: "1.25rem",
        16: "1rem",
      },
      fontSize: {
        "57": "3.563rem",
        "45": "2.813rem",
        "36": "2.25rem",
        "32": "2rem",
        "28": "1.75rem",
        "24": "1.5rem",
        "22": "1.375rem",
        "16": "1rem",
        "14": "0.875rem",
        "12": "0.75rem",
        "11": "0.688rem",
      },
      boxShadow: {
        "3xl": "0 35px 60px -15px rgba(0, 0, 0, 0.3)",
        opaq: "0 4px 16px 6px rgba(0,0,0,0.4)",
        full: "0 3px 1px -2px rgba(0,0,0, 0.2), 0 2px 2px 0 rgba(0,0,0,0.14), 0 1px 5px 0 rgba(0,0,0,0.12)",
        soft: "0 2px 8px -2px rgba(0,0,0,0.08), 0 4px 16px -4px rgba(0,0,0,0.06)",
        glow: "0 0 20px rgba(53, 99, 233, 0.15)",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        heading: ["var(--font-dm-sans)", "DM Sans", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
        montserrat: ["Montserrat", "sans-serif"],
        nunito: ["Nunito", "sans-serif"],
        french: ["IM Fell French Canon", "serif"],
        DmSans: ["DM Sans"],
        roboto: ["Roboto", "sans-serif"],
        lora: ["Lora", "serif"],
      },
      colors: {
        primarykey: "#3563E9",
        onPrimary: "#FFFFFF",
        secondary: "#595D72",
        onSurface: "#1A1B21",
        onSurfaceVariant: "#45464F",
        primaryText: "#637381",
        secondaryText: "#8899A8",
        stroke: "#DFE4EA",
        // Modern design system tokens
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          "0": "var(--primary-color-0)",
          "1": "var(--primary-color-1)",
          "2": "var(--primary-color-2)",
          "3": "var(--primary-color-3)",
          "4": "var(--primary-color-4)",
          "5": "var(--primary-color-5)",
          "6": "var(--primary-color-6)",
          "7": "var(--primary-color-7)",
          "8": "var(--primary-color-8)",
          "9": "var(--primary-color-9)",
          text: "var(--primary-color-text)",
          body: "var(--primary-color-body)",
          background: "var(--primary-color-background)",
          border: "var(--primary-color-border)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
};

export default config;
