import { Box, Button, Flex, Text, TextInput } from "@mantine/core";
import { IconFile, IconMusic } from "@tabler/icons-react";

const images = [
  "https://images.pexels.com/photos/24827102/pexels-photo-24827102.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  "https://images.pexels.com/photos/24514315/pexels-photo-24514315/free-photo-of-a-car-in-the-wilderness.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  "https://images.pexels.com/photos/25039587/pexels-photo-25039587/free-photo-of-a-person-riding-a-bike-through-a-forest.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  "https://images.pexels.com/photos/7566369/pexels-photo-7566369.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
];

const ViewComplaint = ({ complaint }: { complaint: any }) => {
  const handleOpenFullScreen = (document:string) => {
    window.open(document, '_blank', 'noopener,noreferrer');
  };
  return (
    <Flex className="flex-col gap-5">
      <Box className="w-full mx-auto p-8 rounded-lg shadow-md">
        {complaint?.feedback && (
          <Box className="bg-red-100 p-4 rounded">
            <Text className="text-red-700">
              Rejection Reason: {complaint?.feedback}
            </Text>
          </Box>
        )}
        <Box className="flex justify-between items-center mb-4">
          <h1 className="text-2xl font-bold text-primary-default">Title</h1>
          <Box className="text-xl text-primary-default">
            {complaint?.category || "Category"}
          </Box>
        </Box>
        <Box className="mb-6">
          <TextInput
            type="text"
            className="w-full p-2 border rounded"
            value={complaint?.title || "Land Issue"}
          />
        </Box>

        <Box className="flex justify-between items-center mb-4">
          <h2 className="text-xl font-bold text-primary-default">Content</h2>
        </Box>
        <Box className="bg-gray-100 p-4 rounded">
          <Text className="text-gray-700">
            {complaint?.content ||
              `The AI-Generated Image Detection Model can help you determine if an
            image was entirely generated by an AI model, or if it is a real
            image. This model was trained on millions of artificially-created
            and human-created images spanning all sorts of content such as
            photography, art, drawings, memes and more.`}
          </Text>
        </Box>
      </Box>

      <Box className="w-full mx-auto p-8 rounded-lg shadow-md">
        <h2 className="text-xl font-bold text-primary-default  mb-4">Images</h2>
        <Flex className="gap-3 flex-wrap mx-auto">
          {complaint?.imageEvidences?.map((index: any) => (
            <img src={index} key={index} width={200} height={200} alt="image" />
          ))}
        </Flex>
      </Box>
      <Box className="w-full mx-auto p-8 rounded-lg shadow-md">
        <h2 className="text-xl font-bold text-primary-default  mb-4">Audios</h2>
        <Flex className="gap-3 flex-col flex-wrap mx-auto">
          {complaint?.soundTracks?.map((index: any) => (
            <Flex key={index} className="flex-col w-full gap-4">
              <Box className="border-2 flex px-2 py-5 rounded-md gap-5 border-primary-border">
                <IconMusic />
                <Text>Audio Title</Text>
                <audio src={index} controls></audio>
              </Box>
            </Flex>
          ))}
        </Flex>
      </Box>
      <Box className="w-full mx-auto p-8 rounded-lg shadow-md">
        <h2 className="text-xl font-bold text-primary-default  mb-4">Videos</h2>
        <Flex className="gap-3 flex-wrap mx-auto">
          {complaint?.videos?.map((index: any) => (
            <Box key={index}>
              <video width="420" height="240" controls>
                <source src={index} />
                Error Message
              </video>
            </Box>
          ))}
        </Flex>
      </Box>
      <Box className="w-full mx-auto p-8 rounded-lg shadow-md">
        <h2 className="text-xl font-bold text-primary-default  mb-4">
          Documents
        </h2>
        <Flex className="gap-3 flex-wrap mx-auto">
          {complaint?.documents?.map((index: any) => (
            <Flex key={index} className="flex-col">
              <embed src={index} />
              <Text className="text-center">File Title</Text>
              <Button onClick={() => handleOpenFullScreen(index)}>Download</Button>
              
            </Flex>
          ))}
        </Flex>
      </Box>
    </Flex>
  );
};

export default ViewComplaint;
