import { Accordion, ActionIcon, Box, Flex } from "@mantine/core";
import { IconCircleChevronDown } from "@tabler/icons-react";
import ViewComplaint from "./view-complaint";
import { useState } from "react";

const ViewComplaintResponse = ({ complaintLog }: { complaintLog: any }) => {
  const statusClass =
  complaintLog?.priority === "high"
                ? "bg-red-200 text-red-800"
                : complaintLog?.priority === "medium"
                  ? "bg-blue-200 text-blue-800"
                  : "bg-gray-200 text-gray-800";
               
  return (
    <Flex className="flex-col gap-5">
      <Box className="bg-white shadow-md rounded-lg p-6 my-8">
        <Box className="flex justify-between items-end mb-5">
          <h4 className="text-2xl font-semibold text-blue-500">Report Title</h4>
          <Box className="flex flex-col gap-2 items-center">
            <Box className="text-xl font-semibold text-blue-500">Priority</Box>
            <Box className={`text-md ${statusClass} text-blue-500 rounded-full px-4 py-1`}>
              <span
                className={`py-1 px-5 text-center text-xs leading-5 font-semibold rounded-full ${statusClass}`}
              >
                 {complaintLog?.priority || "medium"}
              </span>
            </Box>
          </Box>
        </Box>
        <Box className="bg-gray-100 rounded-lg p-2 mb-4">
          <input
            type="text"
            value={complaintLog?.title || "Land"}
            readOnly
            className="w-full bg-transparent outline-none text-lg"
          />
        </Box>
        <Box className="text-xl font-semibold text-blue-500 mb-2">Content</Box>
        <Box className="bg-gray-100 rounded-lg p-4 mb-4">
          <p className="text-sm text-gray-700">
            {complaintLog?.report || `The AI-Generated Image Detection Model can help you determine if an
            image was entirely generated by an AI model, or if it is a real
            image. This model was trained on millions of artificially-created
            and human-created images spanning all sorts of content such as
            photography, art, drawings, memes and more.`}
          </p>
          
        </Box>

        <Box className="flex justify-end mt-4">
          <Flex className="items-center flex-col">
            <p className="text-xl font-semibold text-blue-500">Status</p>
            <p className="text-md bg-green-100 text-green-500 rounded-full px-4 py-1">
              {complaintLog?.status ||"Resolved"}
            </p>
          </Flex>
        </Box>
      </Box>
      <Accordion
        chevron={
          <ActionIcon size={40} bg="none" pr={14}>
            <IconCircleChevronDown className="text-primary-default text-2xl" />
          </ActionIcon>
        }
        variant="contained"
      >
        <Accordion.Item value="complaint">
          <Accordion.Control>
            <h2 className="text-xl font-bold text-primary-default">
              Complaint Detail
            </h2>
          </Accordion.Control>
          <Accordion.Panel>
            <ViewComplaint complaint={complaintLog?.complaints} />
          </Accordion.Panel>
        </Accordion.Item>
      </Accordion>
    </Flex>
  );
};

export default ViewComplaintResponse;
