import { Box, Flex, Text, TextInput } from "@mantine/core";
import { IconFile, IconMusic } from "@tabler/icons-react";

const images = [
  "https://images.pexels.com/photos/24827102/pexels-photo-24827102.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  "https://images.pexels.com/photos/24514315/pexels-photo-24514315/free-photo-of-a-car-in-the-wilderness.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  "https://images.pexels.com/photos/25039587/pexels-photo-25039587/free-photo-of-a-person-riding-a-bike-through-a-forest.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  "https://images.pexels.com/photos/7566369/pexels-photo-7566369.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
];

const ViewComplaint = ({ complaint }: { complaint: any }) => {
  return (
    <Flex className="flex-col gap-5">
      <Box className="w-full mx-auto p-8 rounded-lg shadow-md">
        <Box className="flex justify-between items-center mb-4">
          <h1 className="text-2xl font-bold text-primary-default">Title</h1>
          <Box className="text-xl text-primary-default">Category</Box>
        </Box>
        <Box className="mb-6">
          <TextInput
            type="text"
            className="w-full p-2 border rounded"
            value="Land Issue"
          />
        </Box>
        <Box className="flex justify-between items-center mb-4">
          <h2 className="text-xl font-bold text-primary-default">Content</h2>
        </Box>
        <Box className="bg-gray-100 p-4 rounded">
          <Text className="text-gray-700">
            The AI-Generated Image Detection Model can help you determine if an
            image was entirely generated by an AI model, or if it is a real
            image. This model was trained on millions of artificially-created
            and human-created images spanning all sorts of content such as
            photography, art, drawings, memes and more.
          </Text>
          <Text className="text-gray-700 mt-2">
            The Model works by analyzing the visual (pixel) content of the
            image. No meta-data is used in the analysis. Tampering with
            meta-data such as EXIF data therefore has no effect on the scoring.
          </Text>
          <Text className="text-gray-700 mt-2">
            The Model was trained to detect images generated by the main models
            currently in use: Stable Diffusion, Stable Diffusion XL, MidJourney,
            Dall-E... Additional models will be added over time as they become
            available.
          </Text>
        </Box>
      </Box>

      <Box className="w-full mx-auto p-8 rounded-lg shadow-md">
        <h2 className="text-xl font-bold text-primary-default  mb-4">Images</h2>
        <Flex className="gap-3 flex-wrap mx-auto">
          {images.map((i, index) => (
            <img src={i} key={index} width={200} height={200} alt="image" />
          ))}
        </Flex>
      </Box>
      <Box className="w-full mx-auto p-8 rounded-lg shadow-md">
        <h2 className="text-xl font-bold text-primary-default  mb-4">Audios</h2>
        <Flex className="gap-3 flex-col flex-wrap mx-auto">
          {images.map((i, index) => (
            <Flex key={index} className="flex-col w-full gap-4">
              <Box className="border-2 flex px-2 py-5 rounded-md gap-5 border-primary-border">
                <IconMusic />
                <Text>Audio Title</Text>
              </Box>
            </Flex>
          ))}
        </Flex>
      </Box>
      <Box className="w-full mx-auto p-8 rounded-lg shadow-md">
        <h2 className="text-xl font-bold text-primary-default  mb-4">Videos</h2>
        <Flex className="gap-3 flex-wrap mx-auto">
          {images.map((i, index) => (
            <Box key={index}>
              <video width="420" height="240" controls>
                <source
                  src="https://videos.pexels.com/video-files/1321208/1321208-hd_1280_720_30fps.mp4"
                  type="video/mp4"
                />
                Error Message
              </video>
            </Box>
          ))}
        </Flex>
      </Box>
      <Box className="w-full mx-auto p-8 rounded-lg shadow-md">
        <h2 className="text-xl font-bold text-primary-default  mb-4">
          Documents
        </h2>
        <Flex className="gap-3 flex-wrap mx-auto">
          {images.map((i, index) => (
            <Flex key={index} className="flex-col">
              <IconFile size="200px" />
              <Text className="text-center">File Title</Text>
            </Flex>
          ))}
        </Flex>
      </Box>
    </Flex>
  );
};

export default ViewComplaint;
