import Provider from "@/providers/Mantine.provider";
import type { Metadata } from "next";
import ReduxProvider from "@/lib/providers";
import { PrimeReactProvider } from "primereact/api";
import { Inter } from "next/font/google";
import "./globals.css";
import { WebSocketProvider } from "@/providers/WebSocketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Complain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrimeReactProvider>
          <ReduxProvider>
            <Provider>
              <WebSocketProvider>{children}</WebSocketProvider>
            </Provider>
          </ReduxProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
